# latest of nginx
FROM nginx:latest
# front end files must be copied to image
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end
# copy to image
COPY ./softy-pinko-front-end.conf  /etc/nginx/conf.d/default.conf